services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 20.18.0
    command: npm run start
    env_file:
      - path: .env
        required: false
    environment:
      NODE_ENV: production
      ADMIN_API_HOST: 0.0.0.0
      ADMIN_API_PORT: 4050
      ADMIN_PUBLIC_URL: https://centralapi.trtelecom.net
    volumes:
      - centralapi_uploads:/app/server/uploads
      - centralapi_data:/app/server/data
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.centralapi.rule=Host(`centralapi.trtelecom.net`)"
      - "traefik.http.routers.centralapi.entrypoints=websecure"
      - "traefik.http.routers.centralapi.tls=true"
      - "traefik.http.services.centralapi.loadbalancer.server.port=4050"

volumes:
  centralapi_uploads:
  centralapi_data:

networks:
  traefik-network:
    external: true
